export const CATEGORY_START_LOADING= "CATEGORY_START_LOADING";
export const CATEGORY_STOP_LOADING= "CATEGORY_STOP_LOADING";
export const CATEGORY_ERROR="CATEGORY_ERROR";
export const CREATE_CATEGORY="CREATE_CATEGORY";
export const GET_ALL_CATEGORY="GET_ALL_CATEGORY";
export const GET_CATEGORY="GET_CATEGORY";
export const UPDATE_CATEGORY="UPDATE_CATEGORY";