export const VARIATION_TYPE_START_LOADING = "VARIATION_TYPE_START_LOADING";
export const VARIATION_TYPE_STOP_LOADING = "VARIATION_TYPE_STOP_LOADING";
export const VARIATION_TYPE_ERROR = "VARIATION_TYPE_ERROR";
export const CREATE_VARIATION_TYPE = "CREATE_VARIATION_TYPE";
export const GET_ALL_VARIATION_TYPE = "GET_ALL_VARIATION_TYPE";
export const GET_VARIATION_TYPE = "GET_VARIATION_TYPE";
export const UPDATE_VARIATION_TYPE = "UPDATE_VARIATION_TYPE";