export const WAREHOUSE_START_LOADING= "WAREHOUSE_START_LOADING";
export const WAREHOUSE_STOP_LOADING= "WAREHOUSE_STOP_LOADING";
export const WAREHOUSE_ERROR="WAREHOUSE_ERROR";
export const CREATE_WAREHOUSE="CREATE_WAREHOUSE";
export const GET_ALL_WAREHOUSE="GET_ALL_WAREHOUSE";
export const GET_WAREHOUSE="GET_WAREHOUSE";
export const UPDATE_WAREHOUSE="UPDATE_WAREHOUSE";