export const PRODUCT_START_LOADING= "PRODUCT_START_LOADING";
export const PRODUCT_STOP_LOADING= "PRODUCT_STOP_LOADING";
export const PRODUCT_ERROR="PRODUCT_ERROR";
export const CREATE_PRODUCT="CREATE_PRODUCT";
export const GET_ALL_PRODUCT="GET_ALL_PRODUCT";
export const GET_PRODUCT="GET_PRODUCT";
export const UPDATE_PRODUCT="UPDATE_PRODUCT";
export const DELETE_PRODUCT = "DELETE_PRODUCT"