export const COMPANY_START_LOADING= "COMPANY_START_LOADING";
export const COMPANY_STOP_LOADING= "COMPANY_STOP_LOADING";
export const COMPANY_ERROR="COMPANY_ERROR";
export const CREATE_COMPANY="CREATE_COMPANY";
export const GET_ALL_COMPANY="GET_ALL_COMPANY";
export const GET_COMPANY="GET_COMPANY";
export const UPDATE_COMPANY="UPDATE_COMPANY";